# -*- coding: utf-8 -*-
"""Límite_Derivada_Integral_Sympy_Básico_cA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-fU1GdfgrKMKxhaKy8X7Y3PZja6af09

# Límite, derivada e Integral de una Función en Python con sympy </center>

Con Actividades para el alumno

Referencias:

* [Calculus con sympy](https://docs.sympy.org/latest/tutorials/intro-tutorial/calculus.html)
* [Uso de IPython.display](https://stackoverflow.com/questions/20979993/how-to-pretty-print-in-ipython-notebook-via-sympy)

---
autor: Roberto Méndez

Editado: 27 Jun 24

# Límites
"""

from sympy import symbols, limit, sin
x  = symbols('x')
limf = limit(sin(x)/x, x, 4)
print("El límite es: ", limf)
###
print("El límite evaluado es: ", limf.evalf())

from sympy import symbols, limit, sqrt
x  = symbols('x')
fx = sqrt(x - 1)
limf = limit(fx, x, 1, '+')
print("El límite es: ", limf)

"""## Actividad:
Problema Interprepas Matemáticas VI área 2

Encuenre el límite de
\begin{equation}
 \lim_{x → 2} \frac{x^2 - 4}{\sqrt{x + 7} - \frac{3}{2}\sqrt{x + 2} }
\end{equation}

# Derivada
"""

from sympy import symbols, diff, sin, exp
x  = symbols('x')
dx = diff(sin(x)/x, x)
print("La derivada es: ", dx)
dxEval = dx.subs(x, 4).evalf()
print("La derivada evaluada en x = 4 es: ", dxEval)

"""Problema Interpreparatoriano Matemáticsa VI área 1

\begin{equation}
 f(x) = \ln \left( \frac{4^{7x^2}}{5e^{3x^5}}\right)
\end{equation}

"""

from sympy import symbols, diff, sin, exp, ln

x  = symbols('x')
fx = ln(4**(7*x**2)/(5*exp(3*x**5)))
dx = diff(fx, x)
print("La derivada es: \n {0}  \n= {1} ".format(dx, dx.simplify()))
#Evaluando en el puntos críticos
#print(
puntoEvaluacion = 0
dxEval = dx.subs(x, puntoEvaluacion).evalf()
print("La derivada evaluada en x = {0} es: {1}".format(puntoEvaluacion, dxEval))
puntoEvaluacion = 1.08967
dxEval = dx.subs(x, puntoEvaluacion).evalf()
print("La derivada evaluada en x = {0} es: {1}".format(puntoEvaluacion, dxEval))

"""Problema Interpreparatoriano Matemáticsa VI área 1

\begin{equation}
 f(x) = \ln \left( \frac{4^{7x^2}}{5e^{3x^5}}\right)
\end{equation}

Con formato de impresión de datos estilo Latex y simplificado.

"""

from IPython.display import display, Latex
from sympy import symbols, diff, sin, exp, ln, latex, Derivative, init_printing
init_printing(use_latex='mathjax')

x  = symbols('x')
derv_x = Derivative(ln(4**(7*x**2)/(5*exp(3*x**5))), x)

print("La derivada es: \n")
result = "$${} ={} = {}$$".format(latex(derv_x),latex(derv_x.doit()),
                                  latex(derv_x.doit().simplify()))
derv_x.doit().subs(x, 0)
display(Latex(result))
#Evaluando en  puntos particulares
puntoEvaluacion = 0
dxEval = derv_x.doit().subs(x, puntoEvaluacion).evalf()
print("La derivada evaluada en x = {0} es: {1}".format(puntoEvaluacion, dxEval))
puntoEvaluacion = 1.08967
dxEval = derv_x.doit().subs(x, puntoEvaluacion).evalf()
print("La derivada evaluada en x = {0} es: {1}".format(puntoEvaluacion, dxEval))

"""## Actividad:
Problema Interprepas Matemáticas VI área 1

Encuenre la derivada de
\begin{equation}
 f(x) = \tan \left( \frac{e^{2\sin(x)}}{4x}\right)^{\sqrt{x}}
\end{equation}

# Integrales

### Usanto la función Intregal
"""

from sympy import symbols, Integral, sin

x  = symbols('x')
intsen =Integral(sin(x), (x,-1,1))
print("El resultado es: ", intsen.evalf())

"""### Usando la función intregate"""



from sympy import symbols, integrate, exp, oo

x  = symbols('x')
print(integrate(exp(-x), (x, 0, oo)))

"""## Actividad:


Encuenre la integral de
\begin{equation}
 \int_{-1}^1\sqrt{1 + x^3}
\end{equation}

"""